// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about_us: defineAsyncComponent(() => import("./AboutUs/index.vue")),
  applications: defineAsyncComponent(() => import("./Applications/index.vue")),
  hero_section: defineAsyncComponent(() => import("./HeroSection/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
});
